### ISSUE TITLE
About the determination of the virtual root joint

### ISSUE THREAD

**Issue by Timkeeper2018** [JLPM22/MotionMatching#1]
hi, I have some doubts about the determination of the virtual root joint. If the Xsens device is calculated with the hip bone as the root joint, can I understand that the original 3D of the hip joint is (0,0,0)? If so how did you establish the ground position? If it is judged by the grounding of the feet, how to deal with the movement of the feet not being grounded?

**Comment by JLPM22** [comment]
Xsens provides the position of the hip joint in a 3D world reference frame. Thus, the hip joint is not always (0,0,0), it has world positions. To compute the virtual root joint we project the position of the hips to the ground by simply removing the Y component. I also have some code to smooth it but I think it is not yet available on this GitHub repository.
