### ISSUE TITLE
Quick Start Failed 

### ISSUE THREAD

**Issue by JinhyunChoi-DEV** [JLPM22/MotionMatching#2]
I used the Unity Engine with 2021.3.24f version.

I tried to add the package using git url which is https://github.com/JLPM22/MotionMatching.git?path=/com.jlpm.motionmatching.

Even if tried many times but it is not working and I got these error messages: 

[Package Manager Window] Cannot perform upm operation: Unable to add package [https://github.com/JLPM22/MotionMatching.git?path=/com.jlpm.motionmatching]:
  Error when executing git command. fatal: not in a git directory
 [NotFound].
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

Could you check about this issue?

**Comment by JLPM22** [comment]
Hi there,

Thank you for reaching out about this issue.

I've just tested the package using Unity 2021.3 and was able to download and import the package correctly. The error message you're seeing often arises when there's an issue with the URL being used.

Maybe there are trailing whitespace or spaces in the URL. The Unity Package Manager is sensitive to this and will fail to find the package if there's any additional whitespace appended. Please double-check the URL you've entered, ensuring there are no extra spaces or characters at the beginning or end.

If the issue persists after confirming the URL, please let me know so we can explore further troubleshooting steps.

**Comment by JinhyunChoi-DEV** [comment]
I solved this issue using this solution
[link](https://stackoverflow.com/questions/72389135/unity-cant-add-git-packages-on-external-ssd-fatal-not-in-a-git-directory)

The problem was git config setting.
After running this command line, the package manager is working!
git config --global --add safe.directory "*"

Thank you for your help!
